language: node_js

notifications:
  email: false

node_js:
  - '8'
  - 9
  - 10
  - 11
  - 12

cache:
  directories:
    - "node_modules"
    - "public"
    - ~/.npm
git:
  depth: 3

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - lint
  - test
  - coverage

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: coverage
      script: npm run coverage

install: npm install